services:
    blog:
        image: ghcr.io/vkrpk/blog-php_app:latest
        depends_on:
            - db
        networks:
            - internal
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.blog.rule=Host(`blog-php.victork.fr`)"
            - "traefik.http.routers.blog.tls=true"
            - "traefik.http.routers.blog.tls.certresolver=lets-encrypt"
            - "traefik.port=80"
    db:
        labels:
            - traefik.enable=false
        ports:
            - "3306:3306"
        image: ghcr.io/vkrpk/blog-php_db:latest
        networks:
            - internal
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_USER=blog-php
            - MYSQL_PASSWORD=blog-php
            - MYSQL_DATABASE=blog-php

volumes:
    mysql:

networks:
    web:
        external: true
    internal:
        external: false

