services:
    app:
        image: ghcr.io/vkrpk/vat-gaming_app:latest
        depends_on:
            - db
        networks:
            - internal
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.vat-gaming.rule=Host(`vat-gaming.victork.fr`)"
            - "traefik.http.routers.vat-gaming.tls=true"
            - "traefik.http.routers.vat-gaming.tls.certresolver=lets-encrypt"
            - "traefik.port=80"
        env_file:
            - .env
    
    database:
        image: mysql
        container_name: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        
volumes:
    mysql:

networks:
    web:
        external: true
    internal:
        external: false

